FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ./ConexaLabs.DesafioBackend.API/ConexaLabs.DesafioBackend.API.csproj ./ConexaLabs.DesafioBackend.API/
COPY ./ConexaLabs.DesafioBackend.Application/ConexaLabs.DesafioBackend.Application.csproj ./ConexaLabs.DesafioBackend.Application/
COPY ./ConexaLabs.DesafioBackend.Core/ConexaLabs.DesafioBackend.Core.csproj ./ConexaLabs.DesafioBackend.Core/
COPY ./ConexaLabs.DesafioBackend.Infrastructure/ConexaLabs.DesafioBackend.Infrastructure.csproj ./ConexaLabs.DesafioBackend.Infrastructure/

RUN dotnet restore "ConexaLabs.DesafioBackend.API/ConexaLabs.DesafioBackend.API.csproj"
COPY . .
WORKDIR "/src/ConexaLabs.DesafioBackend.API"
RUN dotnet build "ConexaLabs.DesafioBackend.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConexaLabs.DesafioBackend.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConexaLabs.DesafioBackend.API.dll"]
